feat: generate specific message depending service type & values
wiremind/wiremind-helm-charts pull request #453
Opened 2024-04-05 14:26 UTC by gabyfulchic

Hey, 

I realized using ingress part on the cerebro helm chart pop this message:
```bash
Upgrading release=cerebro, chart=wiremind/cerebro
Release "cerebro" does not exist. Installing it now.
NAME: cerebro
LAST DEPLOYED: Fri Apr  5 16:03:01 2024
NAMESPACE: coreinfra
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  http://sdb-cerebro.deez.re/
```

Specifically, the `Notes:` part.

After the PR, it should look like that:
```bash
Upgrading release=cerebro, chart=wiremind/cerebro
Release "cerebro" does not exist. Installing it now.
NAME: cerebro
LAST DEPLOYED: Fri Apr  5 17:03:06 2024
NAMESPACE: coreinfra
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
1. Here is your application URL:
   http://sdb-cerebro.deez.re/
```

As when you specify directly the ingress hosts you already have the URL, I added a little logical depending on SVC type & added a space to have a clean output.

2024-04-09 13:06 UTC, capuche2412 requested changes
Hi,
This looks promising ! Can you bump the chart version to `version: 2.0.5` ?

2024-05-24 13:20 UTC, gabyfulchic commented
I'll asap, sorry for the delay!

2024-06-08 15:16 UTC, gabyfulchic commented
Bumped to 2.0.5 :+1:

2024-06-10 10:13 UTC, capuche2412 approved these changes

2024-06-10 10:13 UTC, merged