[ClamAV] Adds PVC and imagePullSecrets
wiremind/wiremind-helm-charts pull request #46
Opened 2021-07-23 08:25 UTC by zedtux

This PR brings 3 new things:

* setting the `imagePullSecrets` avoiding to hit docker servers limitations on downloading images
* setting extra volumes in order to make clamav pod running with the `readOnlyRootFilesystem` as `true` for instance
* choosing to use an `emptyDir` or a `PVC` when mounting the `/data` folder

2021-07-23 11:09 UTC, desaintmartin commented
Thanks for the change! I am not comfortable having Helm managing PVCs, should we simply change this to a statefulset?

2021-07-23 11:14 UTC, zedtux commented
Well, I didn't wanted to change too much things to this Helm chart ... for now as I'm preparing another PR to be able to choose between a `Deployment` or a `DaemonSet`.

Nonetheless it would make much more sense to me too to use a `StatefulSet` instead, so let's do it!

Merci pour ton message 😉

2021-07-26 09:20 UTC, zedtux commented
Hello @desaintmartin,

Here you are with the `StatefulSet`. I've tested it, and it work well.

2021-07-26 09:30 UTC, desaintmartin requested changes

2021-07-26 09:30 UTC, desaintmartin commented on charts/clamav/templates/statefullset.yaml
> +        - name: redis-data
Redis ;)

2021-07-26 09:31 UTC, zedtux commented on charts/clamav/templates/statefullset.yaml
> +        - name: redis-data
Damned ... :)

2021-07-26 09:33 UTC, zedtux commented on charts/clamav/templates/statefullset.yaml
> +        - name: redis-data
Fixed!

2021-07-27 13:00 UTC, desaintmartin commented
It seems you need to bump version (this anti-mining feature on github is very annoying, I have to manually authorize test each time...)

2021-07-27 19:11 UTC, zedtux commented
> It seems you need to bump version

Oh really? That definitely doesn't sound good to me. I'm contributing, you're creating the release.
What if there's another contributor and you'd like to release both contribution together within the same version?

2021-07-27 20:07 UTC, desaintmartin commented
This is actually a "good practice" within the helm community: each merged PR results in a new released version. See the artifact hub for examples! One could argue about the cons and pros, of course.

2021-07-27 20:10 UTC, zedtux commented
Then I will update it tomorrow.

2021-07-28 13:36 UTC, merged

2021-07-28 13:36 UTC, desaintmartin commented
Thanks!

2021-07-28 13:40 UTC, zedtux commented
Can you please let me know when this version will be available on the repo?

2021-07-28 13:45 UTC, desaintmartin commented
CD already released it! Artifact Hub may take ~15 minutes to reload its cache, but `helm repo up` will show it already.